[package]
name = "langchain"
version = "0.1.0"
edition = "2021"
publish = true
repository = "https://github.com/Abraxas-365/langchain-rust"
license = "MIT"
description = "LangChain for Rust, the easiest way to write LLM-based programs in Rust"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.12"
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1.71"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
rusoto_s3 = "0.46.0"
rusoto_textract = "0.46.0"
rusoto_core = "0.46.0"
futures ="0.3"
regex = "1.9.3"
log = "0.4.19"
handlebars = "4.4.0"
html-escape = "0.2.13"
reqwest-eventsource = "0.5.0"
async-openai = "0.18.3"
mockito = "1.3.0"

[dev-dependencies]
tokio-test = "0.4.0"
